### ISSUE TITLE
Error 503 on https://apps.nextcloud.com/api/v1/token

### ISSUE THREAD

**Issue by pbek** [nextcloud/appstore#608]
In the current Chrome and Firefox I get a `POST https://apps.nextcloud.com/api/v1/token 503 (Service Unavailable)` on https://apps.nextcloud.com/developer/apps/releases/new when trying to upload a new release of an app.

## Logs

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
POST https://apps.nextcloud.com/api/v1/token 503 (Service Unavailable)
```

## Steps to reproduce

1. visit https://apps.nextcloud.com/developer/apps/releases/new (and login, in my case via GitHub)
2. enter URL and Signature
3. press `Upload`
4. Nothing happens, beside the errors in the log

**Comment by mtierltd** [comment]
Same here:
token:1 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

**Comment by BernhardPosselt** [comment]
@MorrisJobke

**Comment by pbek** [comment]
<https://apps.nextcloud.com/> now shows a `Service Unavailable` :smiley_cat:

**Comment by MorrisJobke** [comment]
> https://apps.nextcloud.com/ now shows a `Service Unavailable` 😺

That was a little network outage this morning. But should be solved by now.

Regarding the general upload problem: @BernhardPosselt Anything special to look for? Mostly it is the webserver killing the request and a restart of it solves it. Unfortunately there is nothing special to be found in the logs.

**Comment by BernhardPosselt** [comment]
@pbek still happening?

**Comment by pbek** [comment]
> That was a little network outage this morning. But should be solved by now.

yes, it is. https://apps.nextcloud.com/ is up again

> @pbek still happening?

I still get a `POST https://apps.nextcloud.com/api/v1/token 503 (Service Unavailable)`

**Comment by BernhardPosselt** [comment]
No clue, maybe something in the reverse proxy/app server logs?

**Comment by MorrisJobke** [comment]
Could you test again? I did some small modifications.

**Comment by pbek** [comment]
It worked, https://apps.nextcloud.com/apps/ownbackup is updated. Thank you very much, @MorrisJobke and everyone else!

**Comment by R0Wi** [comment]
For me the error still exist when trying to upload a new release for https://apps.nextcloud.com/apps/files_photospheres 
@MorrisJobke i also asked @SudoHenk to upload the release but he got the same error. Any chance to get this fixed?

**Comment by MorrisJobke** [comment]
@R0Wi Does it work again? I guess somebody else looked into it and fixed it in the meantime.

**Comment by R0Wi** [comment]
@MorrisJobke yes, working again, thank you.
