### ISSUE TITLE
Uploading to apps.nextcloud.com fails

### ISSUE THREAD

**Issue by PhieF** [nextcloud/appstore#733]
Hi !

When trying to upload a new version of my app (Carnet) to the nextcloud store, I get these errors
503 Service unavailable
or
500 Internal Server Error

## Details

* Browser and browser version:

Firefox 77 and Chrome

## JavaScript Console Output

[Capture d’écran de 2020-07-16 17-52-54](https://user-images.githubusercontent.com/26841885/87693440-462ea680-c78d-11ea-9b5c-dc79b08e5dd4.png)

## Steps to reproduce

1. just try to upload a new version of an app

Thanks for your work :)

**Comment by afterlogic-support** [comment]
Have just encountered the same issue while trying to upload a new version of our app. Thank you.

**Comment by Rello** [comment]
+1
@MorrisJobke 
Releasing of apps does not work

**Comment by Rello** [comment]
still pending

```
URL: https://apps.nextcloud.com/api/v1/apps/releases
Status: 500 Internal Server Error
```

**Comment by MorrisJobke** [comment]
@Rello Sorry for the problems here. We looked into it and fixed some issues that arose after the migration of the App Store. It should work now a lot better. Could you give it another try?

**Comment by MorrisJobke** [comment]
@Rello @afterlogic-support @PhieF Sorry for the problems here. We looked into it and fixed some issues that arose after the migration of the App Store. It should work now a lot better. Could you give it another try?

**Comment by Rello** [comment]
still not working for me
![Screenshot 2020-07-20 at 15 47 21](https://user-images.githubusercontent.com/13385119/87944951-5ce04080-caa0-11ea-8ddb-7d056d143f10.png)

**Comment by MorrisJobke** [comment]
Ah ... let me check that. It seems that it was still cached on my side.

**Comment by MorrisJobke** [comment]
> still not working for me
> ![Screenshot 2020-07-20 at 15 47 21](https://user-images.githubusercontent.com/13385119/87944951-5ce04080-caa0-11ea-8ddb-7d056d143f10.png)

Mind to try again. There was a permission error for the temporary upload directory.

**Comment by marcelklehr** [comment]
Works for me now. Thank you :blue_heart:

**Comment by MorrisJobke** [comment]
Another app was also successfully released. Let's close this then for now. If there is still a problem releasing a new version, please open a ticket again. Sorry for the inconvenience.

**Comment by Rello** [comment]
worked also for me
thanks!

**Comment by timo1302** [comment]
works for me too
